In [30]:
#numpy
import numpy as np

def matrix_addition(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        print("Matrix dimensions must match for addition.")
    else:
        print("Matrix additon :")
        print(np.add(matrix1, matrix2))

# Function to perform matrix subtraction with boundary check
def matrix_subtraction(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        print("Matrix dimensions must match for subtraction.")
    else:
        print("Matrix Substarction:")
        print(np.subtract(matrix1, matrix2))

# Function to perform scalar matrix multiplication
def scalar_matrix_multiplication(matrix1, matrix2):
    print(np.multiply(matrix1, matrix2))

# Function to perform elementwise matrix multiplication with boundary check
def elementwise_matrix_multiplication(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        print("Matrix dimensions must match for elementwise multiplication.")
    else:
        print("Elementwise Matrix Multiplication :")
        print(np.multiply(matrix1, matrix2))

# Function to perform matrix multiplication with boundary check
def matrix_multiplication(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        print("Number of columns in the first matrix must match the number of rows in the second matrix for multiplication.")
    else:
        print(np.dot(matrix1, matrix2))

# Function to perform matrix transpose
def matrix_transpose(matrix):
    print(np.transpose(matrix))

# Function to find trace of a matrix
def matrix_trace(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square for trace calculation.")
    else:
        print(np.trace(matrix))

# Function to solve linear equations
def solve_linear_equations(coefficients, constants):
    error=False
    if coefficients.shape[0] != coefficients.shape[1]:
        print("Coefficient matrix must be square for linear equation solving.")
        error=True
    if coefficients.shape[0] != constants.shape[0]:
        print("Number of equations must match the number of constants.")
        error=True
    if not error:
        print("Solution is :")
        print(np.linalg.solve(coefficients, constants))

# Function to find the determinant of the matrix 
def matrix_determinant(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square for determinant calculation.")
    else:
        print(np.linalg.det(matrix))   

    
# Function to calculate the inverse of a matrix
def matrix_inverse(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square for trace calculation.")
    else:
        c=np.linalg.det(matrix)
        if (c!=0):
            print(np.linalg.inv(matrix))
        else:
            print("Inverse cannot be found as determinant is zero.")
            
# Function to perform singular value decomposition
def singular_value_decomposition(matrix):
    U, S, VT = np.linalg.svd(matrix)
    print("\nSingular Value Decomposition of Matrix A:")
    print("U:")
    print(U)
    print("S:")
    print(S)
    print("VT:")
    print(VT)

    
# Function to calculate the eigenvalues of a matrix with boundary check
def matrix_eigenvalues(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square for eigenvalue calculation.")
    else:
        print(np.linalg.eigvals(matrix))

def search_element(matrix, element):
    indices = np.where(matrix == element)
    if len(indices[0]) == 0:
        raise ValueError("Element not found in the matrix.")
    return indices


# Function to find the difference between the sum of the upper and lower triangular matrices with boundary check
def triangular_matrix_difference(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        print("Matrix must be square for triangular matrix difference calculation.")
    else:
        upper_sum = np.sum(np.triu(matrix))
        lower_sum = np.sum(np.tril(matrix))
        print("Upper sum is :",upper_sum)
        print("Lower sum is :",lower_sum)
        print("The difference is : ",upper_sum - lower_sum)


m=int(input("Enter the number of rows: "))
n=int(input("Enter the number of columns: "))

mat1=np.empty((m,n)) #creating m*n empty matrices
mat2=np.empty((m,n))


#taking input for matrix 1
print("Matrix 1")
for i in range(m):
    for j in range(n):
        mat1[i,j]=int(input(f"Enter element at position ({i+1},{j+1}): "))

#taking input for matrix 2
print("Matrix 2")
for i in range(m):
    for j in range(n):
        mat2[i,j]=int(input(f"Enter element at position ({i+1},{j+1}): "))
        
print("Matrix 1 : ",mat1)
print("Matrix 2 : ",mat2)

#menu driven program

while True:
    print("1. Matrix Addition\n2. Matrix Subtraction\n3. Scalar Matrix Multiplication\n4. Elementwise Matrix Multiplication")
    print("5. Matrix Multiplication\n6. Matrix Transpose\n7. Trace of a Matrix\n8. Solve System of Linear Equations")
    print("9. Determinant\n10. Inverse\n11. Singular Value Decomposition\n12. Eigen Value\n13. Search an Element")
    print("14. Difference of Sum of Upper and Lower Triangular Matrix\n15. Exit")
    c=int(input("Choose the operation you want to perform from the above menu :"))
    if c==1:
        matrix_addition(mat1,mat2)
        
    elif c==2:
        print("1.Matrix 1-Matrix 2\n2.Matrix 2-Matrix 1\n3.Exit")
        c1=int(input("Enter your choice from the above options: "))
        while True:
            if c1==1:
                matrix_subtraction(mat1,mat2)
                break
            elif c1==2:
                matrix_subtraction(mat2,mat1)
                break
            elif c1==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    
    elif c==3:
        
        print("1.Scalar Multiplication with Matrix 1\n2.Scalar Multiplication with Matrix 2\n3.Exit")
        c2=int(input("Enter your choice from the above options: "))
        while True:
            if c2==1:
                num=int(input(("Enter a scalar for multipliaction :")))
                print("Scalar Matrix Multiplication of Matrix 1 :")
                scalar_matrix_multiplication(mat1,num)
                break
            elif c2==2:
                num=int(input(("Enter a scalar for multipliaction :")))
                print("Scalar Matrix Multiplication of Matrix 2 :")
                scalar_matrix_multiplication(mat2,num)
                break
            elif c2==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
       
    elif c==4:
        elementwise_matrix_multiplication(mat1,mat2)
            
        
    elif c==5:
        print("1.Matrix 1*Matrix 2\n2.Matrix 2*Matrix 1\n3.Exit")
        c3=int(input("Enter your choice from the above options: "))
        while True:
            if c3==1:
                print("Matrix 1 * Matrix 2")
                matrix_multiplication(mat1,mat2)
                break
                  
            elif c3==2:
                print("Matrix 2 * Matrix 1")
                matrix_multiplication(mat2,mat1)
                break
            elif c3==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==6:
        print("1.Transpose of Matrix 1\n2.Transpose of Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Transpose of Matrix 1 : ")
                matrix_transpose(mat1)
                break
            elif c4==2:
                print("Transpose of Matrix 2 : ")
                matrix_transpose(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==7:
        print("1.Trace of Matrix 1\n2.Trace of Matrix 2\n3.Exit")
        c5=int(input("Enter your choice from the above options: "))
        while True:
            if c5==1:
                print("Trace of Matrix 1 : ")
                matrix_trace(mat1)
                break
            elif c5==2:
                print("Trace of Matrix 2 : ")
                matrix_trace(mat2)
                break
            elif c5==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==8:
        m = int(input("Enter the number of equations (m): "))
        n = int(input("Enter the number of variables (n): "))

        # Initialize the coefficient matrix A and the constants vector b
        A = np.empty((m, n))
        b = np.empty(m)

        # Get user input for the coefficient matrix A
        print("Enter the coefficients for the equations:")
        for i in range(m):
            for j in range(n):
                A[i, j] = float(input(f"A[{i + 1},{j + 1}]: "))

        # Get user input for the constants vector b
        print("Enter the constants on the right-hand side:")
        for i in range(m):
            b[i] = float(input(f"b[{i + 1}]: "))

        solve_linear_equations(A,b)
    elif c==9:
        print("1.Determinant of Matrix 1\n2.Determinant of Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Determinant of Matrix 1 : ")
                matrix_determinant(mat1)
                break
            elif c4==2:
                print("Determinant of Matrix 2 : ")
                matrix_determinant(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==10:
        print("1.Inverse of Matrix 1\n2.Inverse of Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Inverse of Matrix 1 : ")
                matrix_inverse(mat1)
                break
            elif c4==2:
                print("Inverse of Matrix 2 : ")
                matrix_inverse(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==11:
        print("1.Singular Value Decomposition of Matrix 1\n2.Singular Value Decomposition of Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Singular Value Decomposition of Matrix 1 : ")
                singular_value_decomposition(mat1)
                break
            elif c4==2:
                print("Singular Value Decomposition of Matrix 2 : ")
                singular_value_decomposition(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==12:
        print("1.Eigen values of Matrix 1\n2.Eigen values of Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Eigen values of Matrix 1 : ")
                matrix_eigenvalues(mat1)
                break
            elif c4==2:
                print("Eigen values of Matrix 2 : ")
                matrix_eigenvalues(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==13:
        print("1.Search in Matrix 1\n2.Search in Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                el=int(input("Enter the value to search : "))
                element_indices = search_element(mat1, el)
                print(f"\nIndices of {element_to_search} in Matrix 1:")
                print(element_indices)
                break
            elif c4==2:
                el=int(input("Enter the value to search : "))
                element_indices = search_element(mat2, el)
                print(f"\nIndices of {element_to_search} in Matrix 2:")
                print(element_indices)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")
    elif c==14:
        print("1.Matrix 1\n2.Matrix 2\n3.Exit")
        c4=int(input("Enter your choice from the above options: "))
        while True:
            if c4==1:
                print("Matrix 1")
                triangular_matrix_difference(mat1)
                break
            elif c4==2:
                print("Matrix 2")
                triangular_matrix_difference(mat2)
                break
            elif c4==3:
                print("Going back to the main menu")
                break
            else:
                print("Enter a valid option !!")

    elif c==15:
        print("Exiting from the program!!")
        break
    else:
          print("Invalid option entered !!")
  

  

Enter the number of rows: 3
Enter the number of columns: 3
Matrix 1
Enter element at position (1,1): 1
Enter element at position (1,2): 2
Enter element at position (1,3): 3
Enter element at position (2,1): 4
Enter element at position (2,2): 5
Enter element at position (2,3): 6
Enter element at position (3,1): 7
Enter element at position (3,2): 8
Enter element at position (3,3): 9
Matrix 2
Enter element at position (1,1): 1
Enter element at position (1,2): 2
Enter element at position (1,3): 3
Enter element at position (2,1): 4
Enter element at position (2,2): 5
Enter element at position (2,3): 6
Enter element at position (3,1): 7
Enter element at position (3,2): 8
Enter element at position (3,3): 9
Matrix 1 :  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Matrix 2 :  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Multiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve System of 